version: 2.1

jobs: 
  build:
    docker:
      - image: cimg/base:2020.01
    steps: 
      - checkout
      - run: npm run lint
  test:
    docker:
      - image: cimg/base:2020.01
    steps: 
      - checkout
      - run: npm run test
  analyse:
    docker:
      - image: cimg/base:2020.01
    steps: 
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyse:
          requires:
            - test
